### ISSUE TITLE
How to merge $append using $merge with $import?

### ISSUE THREAD

**Issue by jmonteiro** [boschni/json-merger#12]
First of all, such an amazing library. Thank you for such a great work, @boschni.

I'm using it to better organize a large library we have in JSON. Because of that, I have some contraints: I have to issue the `json-merger` command line from a single starting file. That means that I am relaying heavily on the use of `$merge` and `$import`.

Let's initially see, on a single file, what I am trying to accomplish. Given:

**a1.json**:

```json
{
  "$merge": {
    "source": {
      "array": [1]
    },
    "with": {
      "array": [
        {
          "$append": 2
        }
      ]
    }
  }
}
```

Running `json-merger --pretty a1.json` I will get:
```json
{
  "array": [
    1,
    2
  ]
}
```

This is exactly what I want. The issue is that I need to split the content of the `with` block to an external file (so I can easily reuse it on many instances).

When I use `$import` for array, I am getting this behavior:

**a2.json**
```json
{
  "$merge": {
    "source": {
      "array": [1]
    },
    "with": {
      "$import": ["b.json"]
    }
  }
}
```

**b2.json**
```json
{
  "array": [
    {
      "$append": 2
    }
  ]
}
```

Running `json-merger --pretty a2.json` I will get:
```json
{
  "array": [
    2
  ]
}
```

Note the missing `1,` from the `array`. **This is not what I intend**, I am trying to have the same behavior as I have with previous run where I have all on the same file.

I can't use `$include` (which would solve the issue in this case) because I need to $import many files, and $include only supports including a single file (which makes sense as it will inject in the current scope). Usually my statements are something like `"with:" { "$import": ["b.json", "c.json", "..."] }`

Is there an alternative to what I'm trying to do?

Thank you in advance.

**Comment by boschni** [comment]
Hi! Thank you for the kind words. Would https://www.npmjs.com/package/data-document-creator help in your case?

**Comment by jmonteiro** [comment]
@boschni while `data-document-creator` is certainly useful, I don't see how it would help in our case as we are merging dozens of JSON files to create one final JSON Schema -- so the output is a single file, which is very straightforward using `json-merger` alone by itself.

We're fully able to merge objects using the $merge & $import directives, our issue is using the $append (and I believe other related ones like $prepend, $insert, among others) with the $merge & $import operations.

**Comment by boschni** [comment]
Ah sorry I thought you were trying to create multiple documents. Currently the `$import` operation is handled as a completely separate `json-merger` command. The output of that command is then merged with the final document. Would it be possible for you to escape the keywords that you want to apply to the final document? I added an example to the test suite here: https://github.com/boschni/json-merger/commit/4ef67ffa0de060fab7861ee027e743f13f57ad8d

**Comment by jmonteiro** [comment]
Perfect! That works great! Thank you a ton 😊 

For future folks looking into this issue, this was solved in my example by changing the `b2.json` into:

```json
{
  "array": [
    {
      "$$append": 2
    }
  ]
}
```
