### ISSUE TITLE
Doesn't work at json-ptr@^1.3.0

### ISSUE THREAD

**Issue by satoruk** [boschni/json-merger#22]
[json-ptr](https://github.com/flitbit/json-ptr/tree/master)@^1.3.0 is breaking change. 

My workaround that i thought, `resolutions` directive of package.json using yarn.

```json
"resolutions": {
  "json-ptr": "1.2.0"
},
```

**Comment by Makatumba** [comment]
We have fixed it in a fork. 
A pull request is opened =D

**Comment by boschni** [comment]
Fixed in 1.1.4 :)

**Comment by satoruk** [comment]
Thanks for your response.
It seems to be working fine 👍🏼
