### ISSUE TITLE
npm audit says it's unsafe

### ISSUE THREAD

**Issue by elcreator** [boschni/json-merger#24]
High          │ Sandbox Breakout / Arbitrary Code Execution                  │
│ Package       │ safe-eval                                                    │
│ Patched in    │ No patch available                                           │
│ Dependency of │ json-merger [dev]                                            │
│ Path          │ json-merger > safe-eval                                      │
│ More info     │ https://npmjs.com/advisories/1033                            │
──────────────────────┘
──────────────────────┐
│ Critical      │ Sandbox Breakout / Arbitrary Code Execution                  │
│ Package       │ safe-eval                                                    │
│ Patched in    │ No patch available                                           │
│ Dependency of │ json-merger [dev]                                            │
│ Path          │ json-merger > safe-eval                                      │
│ More info     │ https://npmjs.com/advisories/1322

**Comment by boschni** [comment]
Yes it seems like `safe-eval` is not as safe as the name suggests ;) It shouldn't be a problem though if you are only merging trusted input or if you are not using expression operations. But maybe there is an alternative to `safe-eval`?

**Comment by scarney81** [comment]
vm2 is a good alternative: https://www.npmjs.com/package/vm2

**Comment by boschni** [comment]
Thanks! Replaced `safe-eval` with `vm2` in release `1.1.6`
