### ISSUE TITLE
Question on merging two arrays with similar keys

### ISSUE THREAD

**Issue by ssarantidis** [boschni/json-merger#3]
Hello boschni,

I have the following question for which I would need your assistance. Is it possible by using the operations you have developped to merge two arrays with same keys but different values?

For example assuming we have:

_a.json:_

```
{
    "array":[
        {
            "a": "a"
        },
        {
            "b": "b"
        }
    ]
}
```

and _b.json_:

```
{
    "array": [
        {
            "a": "b"
        },
        {
            "b": "a"
        }
    ]
}
```

Can I produce the following result? 

```
{
  "array": [
    {
      "a": "a"
    },
    {
      "b": "b"
    },
    {
      "a": "b"
    },
    {
      "b": "a"
    }
  ]
}
```

Does **$append** operation work for array items?

Because by using $append , I only succeed to produce the following result, which is not the desired one (there is an array produced inside the initial _array_ object):

```
{
  "array": [
    {
      "a": "a"
    },
    {
      "b": "b"
    },
    [
    {
      "a": "b"
    },
    {
      "b": "a"
    }
   ]
  ]
}
```

Thank you in advance for your guidance!

Cheers,
Stelios

**Comment by boschni** [comment]
Hi Stelios,

The content of ```b.json``` should be:

```javascript
{
    "array": [
        {
            "$append": {
              "a": "b"
            }
        },
        {
            "$append": {
              "b": "a"
            }
        }
    ]
}
```

Good luck!

**Comment by ssarantidis** [comment]
Thanks a lot, this solution works fine! It would be actually even better if there was a way to avoid adding as many "$append" statements as the amount of array items..

**Comment by wintercounter** [comment]
I would like to reopen this as I'm facing with the same problem. That just looks odd. I would have 2 solutions in mind.:

## 1. It should work with merging by default:
```js
// A
{
    "array": [1]
}

// B
{
    "array": [2]
}

// Result
{
    "array": [1, 2]
}
```
For me it does not make sense to replace values (which it currently does) that way, there's a `$replace` expression for that (and others that can be used for the same purpose).

## 2. Introduce the `$join` expression

```json
{
    "array": {
        "$join": [2]
    }
}
```

**Comment by boschni** [comment]
The current behaviour is actually merging the arrays, but it is merging based on index:

```json
// A
{
    "array": [{ "prop1": 1 }]
}

// B
{
    "array": [{ "prop2": 2 }]
}

// Result
{
    "array": [{ "prop1": 1, "prop2": 2 }]
}
```

I do like the suggestion to add an expression to concatenate arrays without the need to use `$append` everywhere. Maybe call it `$concat` to be consistent with `Array.prototype.concat()`?

```json
// A
{
    "array": [{ "prop1": 1 }]
}

// B
{
    "array": {
      "$concat": [{ "prop2": 2 }]
    }
}

// Result
{
    "array": [{"prop1": 1 }, { "prop2": 2 }]
}
```

**Comment by wintercounter** [comment]
Oops, I wanted to write `$concat` also instead of `$join` :) That solution would be satisfying for me enough.

**Comment by boschni** [comment]
I created a PR for the `$concat`operation, see https://github.com/boschni/json-merger/pull/10 . Can you take a look at it?

**Comment by wintercounter** [comment]
It's cool!
