### ISSUE TITLE
Security vulnerability in `json-ptr@2.x`

### ISSUE THREAD

**Issue by char0n** [boschni/json-merger#41]
This library uses `json-ptr@2.x`. This library suffers with following security vulnerability: https://github.com/advisories/GHSA-8gwj-8hxc-285w

Would it possible to update the `json-ptr` to v3 and release new version of `json-merger`? 

Thanks!

**Comment by boschni** [comment]
Fixed in `1.1.7`

**Comment by char0n** [comment]
Thanks!
