### ISSUE TITLE
Any easy way to skip unserializable values?

### ISSUE THREAD

**Issue by wintercounter** [boschni/json-merger#6]
I'm trying to use this to merge Webpack configs which works great until the point I need to use plugins.

```
plugins: [
    new webpack.Plugin()
]
```

They are being proccessed to JSON also unfortunatelly which breaks Webpack. Would be nice if I would be able to skip these somehow.

```
if (typeof value.constructor === 'function') {
    // skip
}
```

**Comment by wintercounter** [comment]
I've added such feature at my fork: https://github.com/wintercounter/json-merger

Since I'm not sure if this project is dead or not, I'm also not sure to create a PR... In case you give me any signal I'm happy to make a PR and extend tests. After a few weeks I'll publish my version under a new name otherwise.

**Comment by boschni** [comment]
Hi Wintercounter, I would be happy to accept a PR for this functionality. I would add a config parameter such as `--allow-js` though because the package is primarily focused on merging JSON.

**Comment by wintercounter** [comment]
The default functionality now is to `allow-js` basically. In my commits I added `strict: false` by default to the param list which is not a perfect name either. Since to goal is to skip `user-defined` functions I would suggest a `--skip-user-defined` param which is `false` by default.

**Comment by boschni** [comment]
Would this help to fix your issue: https://github.com/boschni/json-merger/compare/feature/strict-object-check ?

**Comment by wintercounter** [comment]
I think it would be fine yes. So this would become default as I can see, right?

**Comment by boschni** [comment]
Yeah as the package is primarily a pure JSON merger, I think it should only process plain objects and not try to process any other instances. Do you agree?

**Comment by wintercounter** [comment]
It's okay from my side.

**Comment by boschni** [comment]
Fix merged and released
