### ISSUE TITLE
Issues with keys prefixed with `$`

### ISSUE THREAD

**Issue by kityan** [boschni/json-merger#9]
Great! But it would be nicer if the lib stops touching other keys with '$' prefix.
I'm trying to merge JSON Schemas and have issues with`$id`, `$schema` and `$ref` keys :)

**Comment by kityan** [comment]
No, sorry for spam. There is another issue. I'm using schemas with 
https://github.com/epoberezkin/ajv-merge-patch and according to it:
```js
  {a: 1, $merge: {source: {b: 2}, with: {c: 3}}}
```
merges into
```js
{a: 1, $merge: {source: {b: 2}, with: {c: 3}}}
```
but your lib merges this into:
```js
{b: 2, c: 3}
```
I think your's lib beaviour is more correct, but it's not suitable for my case.

**Comment by boschni** [comment]
Hi! The library should not touch keys like `$id` as long as the keys do not match an operation like `$merge`. If you actually want to merge objects that contains keys like `$merge`, then you can change the operation prefix to something else like `@`. See: https://github.com/boschni/json-merger#operationprefix-string . Does that help you somehow?
